---
title: "Untitled"
output: html_document
date: "2024-01-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r}
# Load pretend data
data <- data.frame(
  cue = c("ANCESTOR", "BISCUIT", "CANYON", "DIAMETER", "FREEWAY", 
          "LATIN", "LAUNDRY", "MODEL", "PORTRAY", "WELL"),
  target = c("FAMILY", "COOKIE", "MOUNTAIN", "LENGTH", "ROAD", 
             "FRENCH", "SOAP", "CAR", "SHOW", "DONE"),
  condition = c(2, 2, 1, 1, 2, 1, 1, 2, 1, 1),
  study_response = c(NA, NA, "CANYON", "LENGTH", NA, 
                     "FRENCH", "CLEAN", NA, "SHOW", "DONE"),
  study_rt = c(NA, NA, 2530, 2226, NA, 
               2248, 2138, NA, 1568, 1422),
  test_response = c("FAMILY", "COOKIE", "LOW", "LENGTH", "ROAD", 
                    "FRENCH", "SOAP", "CAR", "SHOW", "DONE"),
  test_rt = c(2263, 1812, 2209, 1650, 1473, 
              1528, 2232, 1311, 1262, 1479)
)

data <- data %>% mutate(index = row_number())
# To view the data frame
print(data)
```

```{r}
na_response_a <- data %>% 
      filter(condition == 1) %>% 
      group_by(study_response) %>% 
      add_count() %>%
      filter(n > 3) %>% 
      pull(index)

na_response_b <- data %>%
      filter(condition == 1) %>% 
      filter(nchar(study_response) < 3) %>% 
      pull(index)

na_response_c <- data %>%
      filter(condition == 1) %>% 
      filter(stringdist(tolower(study_response), tolower(cue), method = "lv") < 3) %>% 
      pull(index)

print(na_response_c)

```

```{r}
if (length(na_response_a) != 0 | length(na_response_b) != 0 | length(na_response_c) != 0) {
      remove <- c(na_response_a, na_response_b, na_response_c)
      filtered_data <- data %>%
        filter(!index %in% remove)
    } else{
      filtered_data <- data 
    }
```

```{r}
correct_guess <- filtered_data %>% 
        filter(condition == 1) %>% 
        filter(stringdist(tolower(study_response), tolower(target), method = "lv") < 3) %>% 
        pull(index)
      
clean_data <- filtered_data %>% 
  filter(!index %in% correct_guess)

# Get results
# print("Participant XXXX's Results")
# Calculate accuracy: output: "you performed x% better on ___ items than ___"
## use stringdist to check typos and case
clean_data <- clean_data %>% 
  mutate(correct = case_when(
    stringdist(tolower(test_response), tolower(target), method = "lv") < 3 ~ 1,
    TRUE ~ 0  # Default case if the above condition is not met
  ))
```

```{r}
accuracy <- clean_data %>% 
  group_by(condition) %>% 
  summarize(
    accuracy = sum(correct) / n()
  )

error_acc <- accuracy %>% filter(condition == 1) %>% pull(accuracy)
      study_acc <- accuracy %>% filter(condition == 2) %>% pull(accuracy)
      if (error_acc > study_acc) {
        print(paste0("You performed ", (round(error_acc*100, digits=2) - round(study_acc*100, digits=2)), "% better on error items than study items"))
      } else if (study_acc > error_acc) {
        print(paste0("You performed ", (round(study_acc*100, digits=2) - round(error_acc*100, digits=2)), "% better on study items than error items"))
      } else if (study_acc == error_acc) {
        print("You did just as well on error items as study items")
      }
      print(paste("Error accuracy:", round(error_acc*100, digits=2)))
      print(paste("Study accuracy:", round(study_acc*100, digits=2)))


```

```{r}
# 4) filter for only correct & remove items with rt < 200 and rt > 15000
    # Analyze RT: output: "you responded x% faster on ___ items compared to ___"
    clean_data_rt <- clean_data %>% 
      filter(correct == 1, test_rt > 200, test_rt < 15000) %>% 
      group_by(condition) %>% 
      summarize(
        avg_rt = mean(as.numeric(test_rt))
      )
    
    error_rt <- clean_data_rt %>% filter(condition == 1) %>% pull(avg_rt)
    study_rt <- clean_data_rt %>% filter(condition == 2) %>% pull(avg_rt)
    
    if (error_rt > study_rt) {
      print(paste0("You responsded ", (round(((error_rt - study_rt)/error_rt)*100, digits=2)), "% faster on study items than error items"))
    } else if (study_rt > error_rt) {
      print(paste0("You responded ", (round(((study_rt - error_rt)/study_rt)*100, digits=2)), "% faster on error items than study items"))
    } else if (study_rt == error_rt) {
      print("You responded just as fast on error items as study items")
    }
    
    print(paste("Error response time:", error_rt))
    print(paste("Study response time:", study_rt))
```